### ISSUE TITLE
uv_poll_start failed when bench1 run:./bench1 2000 3000

### ISSUE THREAD

**Issue by mybays** [alexhultman/uWebSockets#73]
echo: src/unix/poll.c:98: uv_poll_start: Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.
Aborted (core dumped)

**Comment by stormwin** [comment]
same error here

**Comment by alexhultman** [comment]
Is this OS X or Linux?

**Comment by stormwin** [comment]
For me, it is Linux

**Comment by mybays** [comment]
Linux,too.

**Comment by alexhultman** [comment]
You are native devs? Running the native server directly?

**Comment by mybays** [comment]
yes,native bench test,if the thread count over 1500,the echo example will crash.

**Comment by alexhultman** [comment]
You modified the number of threads from 10 to 1500?

**Comment by alexhultman** [comment]
Do you have correct ulimit and such? I run bench1 with millions of connections

**Comment by mybays** [comment]
thanks for your clue,i`ll try it tomorrow.

**Comment by alexhultman** [comment]
I'm pretty sure this is about `accept` failing due to the config of the system not allowing that many sockets. Currently I assume that every `accept` returns a valid file descriptor but it can also return -1 on error.

I should add an error check and throw some kind of error when accept fails. Try to fix your configurations.

**Comment by alexhultman** [comment]
ef21f577b70c4224ce437f0e95afb593255d601b

This should probably fix it. I just ignore failed accepts. But this will of course only fix the symptom, not the problem.

**Comment by mybays** [comment]
fixed when i set both client and server:ulimit -n 65536

**Comment by alexhultman** [comment]
Okay but if you reset your configs, can you reproduce the problem with this commit applied?

**Comment by mybays** [comment]
After reset the configs(ulimit -n 1024),the problem fixed with commit applied

**Comment by rfenner** [comment]
I'm still seeing this error on 0.4.1 when the ulimit -n was low. Increasing it the problem went away.
I'm using Linux 4.4.8-20.46.amzn1.x86_64 #1 SMP Wed Apr 27 19:28:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux on EC2.

After I lowered my limit again i'm now getting a segfault instead ot the original error.
From the core dump:
#0  0x0000000000f94610 in uv__io_start (loop=0x7f0dfe0ae7b8 <main_arena+88>,
    w=w@entry=0x31d99f8, events=<optimized out>)
    at ../deps/uv/src/unix/core.c:837
837	../deps/uv/src/unix/core.c: No such file or directory.

**Comment by alexhultman** [comment]
I will take a look at this, maybe you can solve it yourself and send a PR? It should be simple to search for all uv_poll_start and handle eventual errors involved. Should be somewhere around onAcceptable function.

**Comment by rfenner** [comment]
I don't have the time at the moment to try and fix it but looking over the code where I think the issue might be based on whats going on when It crashes it might be in the this status check aroudn 795:
`    uv_poll_init_socket((uv_loop_t *) ((Server *) p->data)->loop, http, clientFd);
    uv_poll_start(http, UV_READABLE, [](uv_poll_t *p, int status, int events) {

        if (status < 0) {
            // error read
        }`

You should probably clean up and return since the start called indicated some error. Instead you go on to try and read from a possibly bad socket. Beyond that I'm not really sure.
If I get the time to try and figure out how to use the compiled node module rather than using npm I'll give it a shot if you haven't fixed it.
